import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";

/**
 * POST — logs a click-through for an affiliate referral link (?ref=CODE on a
 * book detail page). Increments AffiliateReferral.clicks, creating the
 * referral row if a code is used that wasn't pre-generated by the author.
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ slug: string }> },
) {
  try {
    const { slug } = await params;
    const body = await req.json();
    const { domain, refCode } = body;

    if (!domain || !refCode || typeof refCode !== "string") {
      return NextResponse.json({ error: "Invalid request." }, { status: 400 });
    }

    const author = await prisma.author.findFirst({
      where: { OR: [{ slug: domain }, { customDomain: domain }], isActive: true },
      select: { id: true },
    });
    if (!author) return NextResponse.json({ error: "Not found." }, { status: 404 });

    const book = await prisma.book.findFirst({
      where: { authorId: author.id, slug, isPublished: true, affiliateEnabled: true },
      select: { id: true },
    });
    if (!book) return NextResponse.json({ error: "Not found." }, { status: 404 });

    const code = refCode.trim().slice(0, 60);

    await prisma.affiliateReferral.upsert({
      where: { bookId_refCode: { bookId: book.id, refCode: code } },
      create: { bookId: book.id, refCode: code, clicks: 1 },
      update: { clicks: { increment: 1 } },
    });

    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error("[ref-click] Error:", err);
    return NextResponse.json({ error: "Something went wrong." }, { status: 500 });
  }
}
