// AUTO-GENERATED by scripts/gen-theme-hero-manifest.mjs — do not edit by hand.
// Lists theme IDs that have a hero image at public/images/themes/{id}-hero.jpg.
// Regenerated on every build.
export const THEME_HERO_IDS: readonly string[] = ["aviation","mountain-adventure","scuba-diving"];
