// AUTO-GENERATED by scripts/gen-theme-hero-manifest.mjs — do not edit by hand.
// Lists theme IDs that have a hero image at public/images/themes/{id}-hero.jpg.
// Regenerated on every build.
export const THEME_HERO_IDS: readonly string[] = ["aviation","childrens","cinematic","classical","country","electronic","fantasy","hip-hop","jazz","literary","mountain-adventure","nautical","pop","rnb","rock","romance","scifi","scuba-diving","thriller","western"];
